describe('Job Profiles', () => {
  require('./create-job-family.e2e');
  require('./define-job-family-track.e2e');
  require('./create-job-profile-group.e2e');
  require('./create-job-profile.e2e');
  require('./change-job-family-owner.e2e');
  require('./change-job-profile-owner.e2e');
  require('./edit-job-family-name.e2e');
  require('./edit-job-profile-group-name.e2e');
  require('./edit-job-profile-name.e2e');
  require('./add-requirements-to-job-family.e2e');
  require('./add-requirements-to-job-profile.e2e');
  require('./assign-job-family-requirement.e2e');
  require('./assign-job-profile-requirement.e2e');
  require('./remove-job-family-requirement.e2e');
  require('./remove-job-profile-requirement.e2e');
  require('./create-career-matrix.e2e');
  require('./reload-career-matrix.e2e');
});
